# Generated by Django 4.0.1 on 2022-05-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=40)),
                ('datepubli', models.DateTimeField()),
                ('description', models.CharField(max_length=2000)),
                ('category_1', models.CharField(max_length=15, null=True)),
                ('category_2', models.CharField(max_length=15, null=True)),
                ('category_3', models.CharField(max_length=15, null=True)),
                ('category_4', models.CharField(max_length=15, null=True)),
                ('category_environnement', models.BooleanField()),
                ('url', models.URLField(blank=True, null=True)),
                ('site', models.CharField(max_length=20)),
                ('interval_publi', models.CharField(max_length=5, null=True)),
            ],
            options={
                'ordering': ['-datepubli'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=45)),
                ('datepubli', models.DateTimeField()),
                ('url', models.URLField(blank=True, null=True)),
                ('category_environnement', models.BooleanField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media')),
                ('interval_publi', models.CharField(max_length=5, null=True)),
            ],
            options={
                'ordering': ['-datepubli'],
            },
        ),
        migrations.CreateModel(
            name='MediaEnvironnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('url_site', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('Article', 'Article'), ('Media', 'Media'), ('Trading', 'Trading'), ('Tweet', 'Tweet')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=40)),
                ('datepubli', models.DateTimeField()),
                ('url', models.URLField(blank=True, null=True)),
                ('interval_publi', models.CharField(max_length=5, null=True)),
            ],
            options={
                'ordering': ['-datepubli'],
            },
        ),
    ]
