# Generated by Django 4.0.1 on 2022-05-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_media_title_alter_site_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='site'),
        ),
    ]
