# Generated by Django 4.0.1 on 2022-05-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_site_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media'),
        ),
    ]
